# Хорошая статья по настройке postgres compose: https://habr.com/ru/articles/578744/
# Код  в github: https://github.com/mfvanek/useful-sql-scripts/tree/master/running_pg_in_docker

services:
  ## ------------- Postgres (пример с расширенной командой запуска) ---------------------------- ##
#  postgres:
#    container_name: postgres
#    image: docker.io/postgres:${POSTGRES_VERSION}
#    restart: unless-stopped
#    command:
#      - "postgres"
#      - "-c"
#      - "max_connections=50"
#      - "-c"
#      - "shared_buffers=1GB"
#      - "-c"
#      - "effective_cache_size=4GB"
#      - "-c"
#      - "work_mem=16MB"
#      - "-c"
#      - "maintenance_work_mem=512MB"
#      - "-c"
#      - "random_page_cost=1.1"
#      - "-c"
#      - "temp_file_limit=5GB"
#      - "-c"
#      - "log_min_duration_statement=200ms"
#      - "-c"
#      - "idle_in_transaction_session_timeout=10s"
#      - "-c"
#      - "lock_timeout=1s"
#      - "-c"
#      - "statement_timeout=60s"
#      - "-c"
#      - "shared_preload_libraries=pg_stat_statements"
#      - "-c"
#      - "pg_stat_statements.max=10000"
#      - "-c"
#      - "pg_stat_statements.track=all"
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password
#      PGDATA: "/var/lib/postgresql/data/pgdata"
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./init_db:/docker-entrypoint-initdb.d
#      - postgres-data:/var/lib/postgresql/data
#      # volumes:
#    #   - type: tmpfs
#    #     target: /var/lib/postgresql/data
#    #     tmpfs:
#    #       size: 100000000
#    # logging: *logging
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
#      # test: ["CMD", "pg_isready", "-U", "postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    deploy:
#      resources:
#        limits:
#          cpus: '1'
#          memory: 4G
#    networks:
#      - postgres-net

  ## --------------------------------- Postgres --------------------------------- ##
  postgres-db:
    image: docker.io/postgres:${POSTGRES_VERSION}
    container_name: postgres-db
    restart: unless-stopped
    mem_limit: 1600m
    command:
      - "postgres"
      - "-c"
      - "max_connections=16"
    #      - "-p"
    #      - "6432"
    environment:
      POSTGRES_DB: jooq_db
      POSTGRES_USER: jooq_user
      POSTGRES_PASSWORD: jooq_password
    volumes:
      - ./init-script:/docker-entrypoint-initdb.d:Z  #скрипты инициализации БД
      - postgres_data:/var/lib/postgresql/data       # для сохранения в volume
#      - ./postgres-data:/var/lib/postgresql/data:Z  # для сохранения данных БД, вариант с host path (если нужен явный контроль)
    ports:
      - 6432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jooq_user -d jooq_db" ]
      #      test: [ "CMD-SHELL", "pg_isready -U postgres -p 6432 -d nsix" ]
      interval: 10s
      timeout: 10s
      retries: 30
    networks:
      - postgres-net

  # С помощью второго контейнера можно настроить еще базу данных, влить данные и т.д.
  # Но это не обязательно. Лучше использовать скрипты передавая их в docker-entrypoint-initdb.d
#  postgres-init:
#    container_name: postgres-init
#    image: docker.io/postgres:${POSTGRES_VERSION}
#    auto_remove: true
#    restart: no
#    depends_on:
#      postgres:
#        condition: service_healthy
#    command: >
#      sh -c "
#      until pg_isready -h localhost -U postgres -p 5432; do
#      echo 'Waiting for postgres...'
#      sleep 2
#      done
#      psql -v ON_ERROR_STOP=1 -h localhost -p 5432 -U postgres -d postgres -c 'CREATE DATABASE dictionary;'
#      echo 'Database dictionary created successfully'
#      "
#    networks:
#      - postgres-net

  ## ---------------------------- pgadmin (мне не нужно, пользуюсь DBeaver) ---------------------------- ##
  # pgadmin:
  #   # pgAdmin стартует на порту 5050
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4:7.2
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "iamuser@myemail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "pgadmin"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 1G
  #   networks:
  #     - postgres-net

volumes:
  postgres_data:
    name: postgres_data # Для postgres рекомендую named volume
  # pgadmin-data:  

networks:
  postgres-net:
    name: postgres-net
    driver: bridge

  
